import jsPDF from 'jspdf';
import 'jspdf-autotable';

// PDF Export for Proposals
export const exportProposalToPDF = (proposal) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(139, 92, 246); // Purple color
  doc.text('Velox Dynamics', 20, 20);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Elite Engineering Agency', 20, 28);
  
  // Title
  doc.setFontSize(16);
  doc.text('Service Proposal', 20, 45);
  
  // Proposal Details
  doc.setFontSize(11);
  doc.text(`Proposal ID: ${proposal.id}`, 20, 60);
  doc.text(`Date: ${new Date(proposal.createdAt).toLocaleDateString()}`, 20, 68);
  doc.text(`Status: ${proposal.status.toUpperCase()}`, 20, 76);
  
  // Service Details
  doc.setFontSize(14);
  doc.text('Service Details', 20, 92);
  doc.setFontSize(10);
  
  const serviceDetails = [
    ['Service Type', proposal.serviceType],
    ['Project Title', proposal.projectTitle || 'N/A'],
    ['Budget', `$${proposal.budget || 'Not specified'}`],
    ['Timeline', proposal.timeline || 'To be determined']
  ];
  
  doc.autoTable({
    startY: 98,
    head: [['Field', 'Value']],
    body: serviceDetails,
    theme: 'grid',
    headStyles: { fillColor: [139, 92, 246] },
    margin: { left: 20 }
  });
  
  // Description
  const finalY = doc.lastAutoTable.finalY || 98;
  doc.setFontSize(14);
  doc.text('Description', 20, finalY + 15);
  
  doc.setFontSize(10);
  const splitDescription = doc.splitTextToSize(proposal.description || 'No description provided', 170);
  doc.text(splitDescription, 20, finalY + 23);
  
  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Velox Dynamics Platform', 20, pageHeight - 10);
  doc.text(new Date().toLocaleString(), 150, pageHeight - 10);
  
  // Save
  doc.save(`proposal-${proposal.id}.pdf`);
};

// PDF Export for Requests
export const exportRequestToPDF = (request) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(139, 92, 246);
  doc.text('Velox Dynamics', 20, 20);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Elite Engineering Agency', 20, 28);
  
  // Title
  doc.setFontSize(16);
  doc.text('Service Request', 20, 45);
  
  // Request Details
  doc.setFontSize(11);
  doc.text(`Request ID: ${request.id}`, 20, 60);
  doc.text(`Date: ${new Date(request.createdAt).toLocaleDateString()}`, 20, 68);
  doc.text(`Status: ${request.status.toUpperCase()}`, 20, 76);
  
  // Service Details
  doc.setFontSize(14);
  doc.text('Request Details', 20, 92);
  doc.setFontSize(10);
  
  const requestDetails = [
    ['Service Type', request.serviceType],
    ['Project Name', request.projectName || 'N/A'],
    ['Budget Range', request.budgetRange || 'Not specified'],
    ['Timeline', request.timeline || 'Flexible'],
    ['Priority', request.priority || 'Normal']
  ];
  
  doc.autoTable({
    startY: 98,
    head: [['Field', 'Value']],
    body: requestDetails,
    theme: 'grid',
    headStyles: { fillColor: [139, 92, 246] },
    margin: { left: 20 }
  });
  
  // Description
  const finalY = doc.lastAutoTable.finalY || 98;
  doc.setFontSize(14);
  doc.text('Requirements', 20, finalY + 15);
  
  doc.setFontSize(10);
  const splitDescription = doc.splitTextToSize(request.requirements || 'No requirements specified', 170);
  doc.text(splitDescription, 20, finalY + 23);
  
  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Velox Dynamics Platform', 20, pageHeight - 10);
  doc.text(new Date().toLocaleString(), 150, pageHeight - 10);
  
  // Save
  doc.save(`request-${request.id}.pdf`);
};

// CSV Export for Data Tables
export const exportToCSV = (data, filename = 'export.csv') => {
  if (!data || data.length === 0) {
    console.error('No data to export');
    return;
  }
  
  // Get headers from first object
  const headers = Object.keys(data[0]);
  
  // Create CSV content
  let csvContent = headers.join(',') + '\n';
  
  data.forEach(row => {
    const values = headers.map(header => {
      const value = row[header];
      // Handle values with commas or quotes
      if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
        return `"${value.replace(/"/g, '""')}"`;
      }
      return value;
    });
    csvContent += values.join(',') + '\n';
  });
  
  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Print View Helper
export const openPrintView = (content, title = 'Document') => {
  const printWindow = window.open('', '_blank');
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 40px;
            color: #333;
          }
          h1 {
            color: #8B5CF6;
            border-bottom: 2px solid #8B5CF6;
            padding-bottom: 10px;
          }
          h2 {
            color: #666;
            margin-top: 30px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
          }
          th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
          }
          th {
            background-color: #f4f4f4;
            font-weight: bold;
          }
          .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #999;
          }
        </style>
      </head>
      <body>
        ${content}
        <div class="footer">
          <p>Generated by Velox Dynamics Platform on ${new Date().toLocaleString()}</p>
        </div>
        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
};
